sudo: required
services:
        - docker

before_install:
        - docker build -t aiigii01/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true aiigii01/docker-react npm run test

language: generic 
